### PR TITLE
Cndit 1446 - nrt database objects

### PR DESCRIPTION
**Pull request by rseshadri99**
This commit has all the odse/rdb database objects needed for RTR Pipeline

### CODE REVIEW

**Review by upasanapattnaik-eq — COMMENTED** [review]
Will these be added into the changelog file in a later sprint? Or are these primarily for version control?

**Comment by rseshadri99** [comment]
Yes later sprint once Sergei validates the functionality of liquibase

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by upasanapattnaik-eq — APPROVED** [review]
Looks good to me! 
Thank you for the update. Lots of sprocs 💯

**Comment by rseshadri99** [comment]
Updates to database objects required for rtr pipeline for both odse and rdb databases's

**Pull request merged**
